export 'package:forms_app/presentation/screens/home/home_screen.dart';
export 'package:forms_app/presentation/screens/cubit/cubit_screen.dart';
export 'package:forms_app/presentation/screens/bloc/bloc_screen.dart';
export 'package:forms_app/presentation/screens/provider/provider_screen.dart';
export 'package:forms_app/presentation/screens/riverpod/riverpod_screen.dart';
export 'package:forms_app/presentation/screens/form/traditional_form.dart';
export 'package:forms_app/presentation/screens/form/state_gesture_form.dart';
export 'package:forms_app/presentation/screens/form/custom_state_gesture_form.dart';
export 'package:forms_app/presentation/screens/form/custom_state_gesture_form_auto.dart';
